version: "3.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:4.89.0
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ./Projects:/config/workspace
    ports:
      - 8443:8443
    restart: unless-stopped
